# fly.toml app configuration file generated for si-cheong on 2025-04-25T20:08:13+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'si-cheong'
primary_region = 'nrt'

[build]
[build.args]
GO_VERSION = '1.24.1'

[env]
PORT = '8081'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[mounts]
source = "litefs"
destination = "/var/lib/litefs"
